name: Dependency updater

on:
  schedule:
    - cron: '0 0 * * 0'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: deps-updater
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Update dependencies
        run: build/deps/update-deps.py
      - name: Open pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "update dependencies to latest version"
          branch: "automatic-update-deps"
          title: "Update dependencies"
          body: |
            This is an automated pull request for updating the dependencies of workerd.
          delete-branch: true
